### ISSUE TITLE
Since 15/03/2022 is not working with an error on openoing global address list

### ISSUE THREAD

**Issue by paochiz** [grahamr975/EWS-Office365-Contact-Sync#53] opened 2022-03-23 10:33 UTC
Write-Log : Failed to fetch Global Address List Contacts from Office 365 Directory
In riga:77 car:3
+         Write-Log -Level "FATAL" -Message "Failed to fetch Global Add ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Write-Log

**Comment by grahamr975** [comment] 2022-03-23 11:26
Closed as duplicate of issue #52

**Closed** 2022-03-23 11:26 UTC
