### ISSUE TITLE
Failed to fetch Global Address List Contacts from Office 365

### ISSUE THREAD

**Issue by landregen** [grahamr975/EWS-Office365-Contact-Sync#7] opened 2020-01-23 18:24 UTC
When i try to use the script, i've the error :

`Write-Log : Failed to fetch Global Address List Contacts from Office 365
Directory
Au caractère Ligne:50 : 3
+         Write-Log -Level "FATAL" -Message "Failed to fetch Global Address
List Contact ...
+    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorExcep
   tion
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorExceptio
   n,Write-Log`

**Comment by grahamr975** [comment] 2020-01-23 21:53
I'm not able to reproduce this error.

- Are you using an account with application impersonation?
-Did you install the EWS API?
-Did you create a credential file?
-What environment are you in? This script is only designed to work with O365 Exchange, not locally hosted

**Comment by landregen** [comment] 2020-01-24 10:24
1) Yes the accaount have application impersonation right
2) The EWS was installed
3 ) Yes i use a credential file
4) I'm in a Office 365 environment

**Comment by supersmink** [comment] 2020-01-25 19:22
I've had the same issue, and have fixed by adding -AllowClobber to Line 36 of _\EWSContacts\Module\functions\contactsGet-GALContacts.ps1_

Line 36 now reads: Import-PSSession $Session -DisableNameChecking **-AllowClobber**

**Comment by grahamr975** [comment] 2020-01-27 15:29
After some testing, I've implemented @supersmink's bugfix into the script.

@Landregen, please download the latest version and confirm that this issue is resolved for you.

**Comment by grahamr975** [comment] 2020-01-31 18:55
Closing this issue due to lack of reply...

**Closed by grahamr975** 2020-01-31 18:55 UTC
Labels: bug
